import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { AppProps } from 'next/app'



export default function Home() {
  return (
    <>
      <Head>
        <title>Grateful AI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
      <div className=' text-emerald-900 '>hey next</div>
      </main>
    </>
  )
}
